### PR TITLE
updated contuibuting.md

### PR DESCRIPTION
**Pull request by anees1203**
Testing,CI/CD Pipeline and Dependencies were added and moreover added a simple road map for contributors

### CODE REVIEW

**Comment by DemonXslayer47** [comment]
The Dependencies might change according to the programming language we use in our project. Right now we don't use react and node js files. So you might change those accordingly.
Thank you.

**Comment by anees1203** [comment]
yes, you are right. I will change it
Thanks for letting me know.

**Comment by anees1203** [comment]
Created Servant as Leader Evaluation

**Comment by anees1203** [comment]
Updated etl typescript and created some files related to transactions components

**Pull request merged**
